// Shared select configuration for seller product forms that need nested media and variant metadata.
export const sellerProductFormSelect = {
  id: true,
  title: true,
  handle: true,
  status: true,
  channel: true,
  channelStatus: true,
  channelProductId: true,
  channelHandle: true,
  channelSettings: true,
  channelPublishingErrors: true,
  seller: { id: true, name: true },
  shop: { id: true, name: true },
  order: { id: true, orderId: true },
  vendorCode: true,
  vendorProductId: true,
  productType: true,
  productCategory: true,
  category: true,
  tags: true,
  templateSuffix: true,
  hasVariantsThatRequiresComponents: true,
  trackInventory: true,
  continueSellingWhenOutOfStock: true,
  body: { markdown: true, truncatedHTML: true },
  publishedAt: true,
  updatedAt: true,
  compareAtPriceRange: true,
  generatedImages: true,
  designAssignments: true,
  designId: true,
  mockupConfig: true,
  mockupAssets: true,
  optionsData: true,
  variantsData: true,
  mediaData: true,
  customCollections: true,
  seoTitle: true,
  seoDescription: true,
  options: {
    edges: {
      node: {
        id: true,
        name: true,
        position: true,
        values: true,
      },
    },
  },
  variants: {
    edges: {
      node: {
        id: true,
        title: true,
        sku: true,
        barcode: true,
        price: true,
        compareAtPrice: true,
        cost: true,
        unitCost: true,
        position: true,
        availableForSale: true,
        taxable: true,
        taxCode: true,
        inventoryPolicy: true,
        inventoryQuantity: true,
        requiresShipping: true,
        hsCode: true,
        weight: true,
        weightUnit: true,
        optionLabels: true,
        option1: true,
        option2: true,
        option3: true,
        selectedOptions: true,
        presentmentPrices: true,
        designId: true,
        mockupConfig: true,
        inventoryItem: { id: true, sku: true },
        media: {
          edges: {
            node: {
              id: true,
              alt: true,
              position: true,
              file: { id: true, filename: true },
            },
          },
        },
      },
    },
  },
  media: {
    edges: {
      node: {
        id: true,
        alt: true,
        position: true,
        file: { id: true, filename: true },
      },
    },
  },
} as const;

export type SellerProductFormSelect = typeof sellerProductFormSelect;
