import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.4.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2025-10",
        enabledModels: [
          "shopifyApp",
          "shopifyAppCredit",
          "shopifyAppInstallation",
          "shopifyAppPurchaseOneTime",
          "shopifyAppSubscription",
          "shopifyAppUsageRecord",
          "shopifyBulkOperation",
          "shopifyCarrierService",
          "shopifyCatalog",
          "shopifyCollect",
          "shopifyCollection",
          "shopifyCustomer",
          "shopifyCustomerAddress",
          "shopifyDeliveryMethod",
          "shopifyExchangeLineItem",
          "shopifyFile",
          "shopifyFulfillment",
          "shopifyFulfillmentEvent",
          "shopifyFulfillmentHold",
          "shopifyFulfillmentLineItem",
          "shopifyFulfillmentOrder",
          "shopifyFulfillmentOrderDestination",
          "shopifyFulfillmentOrderLineItem",
          "shopifyFulfillmentOrderMerchantRequest",
          "shopifyFulfillmentService",
          "shopifyInventoryItem",
          "shopifyInventoryLevel",
          "shopifyInventoryQuantity",
          "shopifyLocation",
          "shopifyOrder",
          "shopifyOrderAdjustment",
          "shopifyOrderLineItem",
          "shopifyOrderTransaction",
          "shopifyPage",
          "shopifyPriceList",
          "shopifyPriceListPrice",
          "shopifyProduct",
          "shopifyProductMedia",
          "shopifyProductOption",
          "shopifyProductVariant",
          "shopifyProductVariantMedia",
          "shopifyQuantityPriceBreak",
          "shopifyRedirect",
          "shopifyRefund",
          "shopifyRefundDuty",
          "shopifyRefundLineItem",
          "shopifyReturn",
          "shopifyReturnLineItem",
          "shopifyReturnShippingFee",
          "shopifyReverseDelivery",
          "shopifyReverseDeliveryLineItem",
          "shopifyReverseFulfillmentOrder",
          "shopifyReverseFulfillmentOrderDisposition",
          "shopifyReverseFulfillmentOrderLineItem",
          "shopifyScriptTag",
          "shopifyShippingLine",
          "shopifyTenderTransaction",
        ],
        type: "partner",
        scopes: [
          "read_customers",
          "write_customers",
          "read_orders",
          "write_orders",
          "read_fulfillments",
          "read_returns",
          "read_products",
          "write_products",
          "write_app_proxy",
          "write_content",
          "read_content",
          "read_online_store_navigation",
          "write_files",
          "read_files",
          "write_fulfillments",
          "write_inventory",
          "read_inventory",
          "read_locations",
          "write_inventory_shipments",
          "read_inventory_shipments",
          "write_inventory_transfers",
          "read_inventory_transfers",
          "write_locations",
          "write_metaobject_definitions",
          "read_metaobject_definitions",
          "write_metaobjects",
          "read_metaobjects",
          "write_order_edits",
          "read_order_edits",
          "write_price_rules",
          "read_price_rules",
          "read_product_listings",
          "write_purchase_options",
          "read_purchase_options",
          "write_returns",
          "write_script_tags",
          "read_script_tags",
          "write_shipping",
          "read_shipping",
          "write_assigned_fulfillment_orders",
          "read_assigned_fulfillment_orders",
        ],
        customerAuthenticationEnabled: true,
      },
    },
    authentications: {
      settings: {
        redirectOnSignIn: "/signed-in",
        signInPath: "/sign-in",
        unauthorizedUserRedirect: "signInPath",
        defaultSignedInRoles: ["signed-in"],
      },
      methods: {
        emailPassword: true,
        googleOAuth: {
          scopes: ["email", "profile"],
          offlineAccess: false,
        },
      },
    },
  },
};
