# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "19afcc1d710d312d88a74f94fd180eab"
name = "Multi Vendor OMS Dev"
application_url = "https://omspoint--development.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = ["https://omspoint--development.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact" ,"shop/redact"]
uri = "https://omspoint--development.gadget.app/api/webhooks/shopify"
